# 1. 부동소수점(FPU) 하드웨어 지원 활성화
CONFIG_FPU=y

# 2. C 표준 라이브러리 설정 (Newlib 제거, Picolibc 명시)
CONFIG_PICOLIBC=y

# 3. 콘솔(터미널) 출력 및 Float 출력 지원 (Picolibc 환경에서도 필수)
CONFIG_STDOUT_CONSOLE=y
CONFIG_CBPRINTF_FP_SUPPORT=y

# 4. 메인 스레드 스택 사이즈 확보
CONFIG_MAIN_STACK_SIZE=4096

# 5. RISC-V 벡터 확장(RVV) 활성화
#CONFIG_RISCV_ISA=y

# QEMU 가상 머신 실행 시 사용할 추가 플래그 (벡터 하드웨어 강제 장착)

CONFIG_QEMU_EXTRA_FLAGS="-cpu rv32,v=true,vlen=128,vext_spec=v1.0"
#CONFIG_QEMU_EXTRA_FLAGS="-machine virt -bios none -m 256-cpu max,len=64 -nographic -kernel build/zephyr/zephyr.elf"

# 6. 전원 관리 기능 활성화 (필수는 아니지만, 시스템 안정성 향상에 도움)
#CONFIG_POWEROFF=y
#CONFIG_PM_DEVICE=y
#CONFIG_EVENTS=y
#CONFIG_PM=y
#CONFIG_GPIO=y
#CONFIG_CRC=y
